start = xml
xml = element xml { source, poem }

source = element source { title, author, date }
poem = element poem { title, lg+ }

title = element title { attribute level { "book" | "inner" }, text }
author = element author { text }
date = element date { attribute when { xsd:gYear } }

lg = element lg { ln+ }
ln = element ln { attribute n { xsd:integer }, mixed { (placeName | place | motif)* } }

placeName = element placeName { attribute ref { text }, text }
place = element place { attribute ref { text }, text }
motif = element motif { text }
